#! /usr/bin/env python3
"""ImmoSearch Daemon."""

from immosearch.config import CONFIG
from immosearch.wsgi import APPLICATION


if __name__ == '__main__':
    HOST = CONFIG['wsgi']['host']
    PORT = int(CONFIG['wsgi']['port'])
    APPLICATION.run(host=HOST, port=PORT)
